services:
  node-app:
    build: .
    ports:
      - "9229:9229" # Debugger port mapping
    volumes:
      - ./:/app:cached  # :cached for Windows
      - /app/node_modules
    command: npm run dev

  redis-cache:
    ports:
    - "6379:6379"
