services:
  node-app:
    build: .
    ports:
      - "3000:3000" # App port mapping
    environment:
      - PORT=3000
    depends_on:
      - redis-cache
  
  redis-cache:
    image: redis:alpine
    container_name: redis-cache
